#pragma once

#include "IrBuffersAutoGenerated.h"

class ImageDescriptions
{
public:

    static juce::String getDescription(int irIndex)
    {
        if (irIndex >= IrBuffers::getIrCount())
            return juce::String("");

        if (irIndex == 0)
        {
            return juce::String("A unitary impulse, whose value is zero everywhere except at zero. When convolved with any signal, the result is the signal itself.");
        }
        if (irIndex == 1)
        {
            return juce::String("A function composed by 2 impulses, one of them at zero, and the other one some samples after. When convolved with any signal, the result is the signal itself, plus a delayed copy of it.");
        }
        
		return juce::String("");
    }
};
