#pragma once

#include "pluginterfaces/base/fplatform.h"

//////////////////////////////////////////////////////////////////////////////

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Barcelona Reverbera.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Barcelona Reverbera VST3 (64Bit)"
#else
#define stringFileDescription	"Barcelona Reverbera VST3"
#endif
#define stringCompanyName		"sbrk devices\0"
#define stringLegalCopyright	"Copyright(c) 2024 sbrk devices"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"

//////////////////////////////////////////////////////////////////////////////
